# Generated by Django 5.2.5 on 2025-08-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='FoodPlace',
        ),
    ]
